---
site:
  title: DAG-OS Documentation
  url: https://dag-os.github.io/pages
  start_page: dagos.git::index.adoc
content:
  sources:
    - url: https://github.com/DAG-OS/ansible-role-git
      branches: [trunk, v*]
      start_paths:
        - docs/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
